import { FbrainError, recordTypeForHash, stripDoctorTip, type NativeIndexHit, type NodeClient, type Verbose } from "../../client.ts";
import type { Config } from "../../config.ts";
import { decodeCapabilityBlob, FBRAIN_APP_ID, tokenIntegrityValid, type CapabilityStore } from "../../capability.ts";
import { listRecords, nowIso, verifyRecordVisible, TOMBSTONE_TAG } from "../../record.ts";
import type { RecordType } from "../../schemas.ts";
import { MIN_BUN_VERSION, bunVersionMeetsMinimum } from "../../runtime.ts";
import { appIdentityEnforceEnabled, newWriteNodeClient, type WriteNodeClientOptions } from "../../write-context.ts";
import { buildTombstoneFields } from "../delete.ts";
import type { CheckResult, DoctorOptions } from "../doctor.ts";

export async function runEmbeddingProbe(
  node: NodeClient,
  verbose: Verbose | undefined,
): Promise<CheckResult> {
  try {
    const hits = await node.search("fbrain", { localFallback: false });
    verbose?.(`embedding-runtime: ok (${hits.length} hits to probe query)`);
    return {
      name: "embedding-runtime",
      ok: true,
      detail: "one-token search returned without an embedding-model error",
    };
  } catch (err) {
    if (err instanceof FbrainError && err.code === "embedding_model_unavailable") {
      return {
        name: "embedding-runtime",
        ok: false,
        detail: stripDoctorTip(err.message),
        fix:
          err.hint ??
          "restart the node so it re-fetches the ONNX file (homebrew: `lastdb daemon stop && lastdb daemon start`)",
      };
    }
    if (err instanceof FbrainError && err.code === "node_http_404") {
      return {
        name: "embedding-runtime",
        ok: true,
        tag: "WARN",
        detail: "Search app endpoint is unavailable; fbrain search will use local query fallback",
        fix:
          "upgrade the LastDB node to a build that serves the Search app route, or continue with local keyword fallback for Brain dedupe/search",
      };
    }
    return {
      name: "embedding-runtime",
      ok: false,
      detail: stripDoctorTip(errMsg(err)),
      fix: "check the node log; the Search app route is rejecting the probe query",
    };
  }
}

// G3a — freshness probe. Five trials of put → search; each trial passes
// when the freshly-written record surfaces in the top-K of a search for a
// unique marker word at score ≥ freshnessMinScore (default 0.5). The overall
// verdict is variance-tolerant: it PASSes on a healthy average score
// (≥ minScore) AND a majority of trials surfacing, so normal per-trial
// embedding-score noise on a healthy fresh brain does not flip it to a flaky
// FAIL — while writes that don't surface at all, or a systematically low
// average, still FAIL loudly. Probes are soft-deleted in a
// finally block so a thrown error mid-trial still cleans up. See
// docs/phase-7-search-latency-spike.md G3a.
export async function runFreshnessProbe(
  node: NodeClient,
  cfg: Config,
  opts: DoctorOptions,
  verbose: Verbose | undefined,
): Promise<CheckResult> {
  const trials = opts.freshnessTrials ?? 5;
  const minScore = opts.freshnessMinScore ?? 0.5;
  const nonce = (opts.nonceFn ?? defaultNonce)();
  const conceptHash = cfg.schemaHashes.concept;
  if (!conceptHash) {
    return {
      name: "freshness-probe",
      ok: false,
      detail: 'config has no schemaHashes["concept"]',
      fix: "re-run `fbrain init` so the config picks up all schema hashes",
    };
  }

  type TrialResult = {
    slug: string;
    marker: string;
    found: boolean;
    score: number | null;
    pass: boolean;
  };
  const created: string[] = [];
  const trialResults: TrialResult[] = [];

  let searchError: string | null = null;
  try {
    for (let i = 0; i < trials; i++) {
      const slug = `doctor-freshness-probe-${nonce}-${i}`;
      const marker = `freshprobe${nonce}${i}`;
      const body =
        `Doctor freshness probe trial ${i}. Marker word: ${marker}. ` +
        `Generated by \`fbrain doctor --freshness\` — safe to delete.`;
      const now = nowIso();
      // Phase E per-kind Concept schema declares 7 fields: slug, title, body,
      // status, tags, created_at, updated_at. The legacy `kind` discriminator
      // and `v1_marker_a/b` structural markers are intentionally absent.
      const fields: Record<string, unknown> = {
        slug,
        title: `freshness probe ${i}`,
        body,
        status: "active",
        tags: [],
        created_at: now,
        updated_at: now,
      };
      await node.createRecord({ schemaHash: conceptHash, fields, keyHash: slug });
      created.push(slug);

      let hits: NativeIndexHit[];
      try {
        hits = await node.search(marker);
      } catch (err) {
        // The native-index search endpoint can fail independently of the
        // write path (e.g. node's embedding model.onnx is missing). Capture
        // the first failure as the probe's headline detail and stop trialing
        // — every subsequent trial would hit the same error. The `finally`
        // block still tombstones the records we already created.
        searchError = errMsg(err);
        verbose?.(
          `freshness trial ${i + 1}/${trials}: search threw — ${searchError}`,
        );
        break;
      }
      const own = hits.find(
        (h) => h.key_value.hash === slug && h.schema_name === conceptHash,
      );
      const score =
        own && typeof own.metadata?.score === "number" ? own.metadata.score : null;
      const found = own !== undefined;
      const pass = found && typeof score === "number" && score >= minScore;
      trialResults.push({ slug, marker, found, score, pass });
      verbose?.(
        `freshness trial ${i + 1}/${trials}: ${pass ? "PASS" : "FAIL"} ` +
          `slug=${slug} marker=${marker} found=${found} score=${score ?? "—"}`,
      );
    }
  } finally {
    for (const slug of created) {
      try {
        const cleanupFields = buildTombstoneFields("concept", slug, nowIso(), nowIso());
        await node.updateRecord({ schemaHash: conceptHash, fields: cleanupFields, keyHash: slug });
      } catch (err) {
        verbose?.(
          `freshness cleanup failed for ${slug}: ${errMsg(err)}`,
        );
      }
    }
  }

  if (searchError !== null) {
    return {
      name: "freshness-probe",
      ok: false,
      detail: `native-index search failed: ${searchError}`,
      fix: "the node's native-index search is unavailable (e.g. missing embedding model.onnx). Check the node log; restart the node with embeddings enabled.",
    };
  }

  const passed = trialResults.filter((t) => t.pass).length;
  const scored = trialResults.filter((t): t is TrialResult & { score: number } => t.score !== null);
  const avgScore =
    scored.length > 0
      ? scored.reduce((s, t) => s + t.score, 0) / scored.length
      : null;
  const detail =
    `${passed}/${trials} trial${trials === 1 ? "" : "s"} passed` +
    ` (min score ≥ ${minScore}; ` +
    (avgScore === null ? "no scores observed" : `avg observed score ${avgScore.toFixed(3)}`) +
    ")";

  // Variance-tolerant verdict. The all-trials-must-clear-0.5 gate was
  // non-deterministic on a perfectly healthy fresh brain: per-trial embedding
  // scores hover around ~0.6 and one (occasionally two) trials dipping below
  // the floor by normal noise flipped the whole verdict to a red FAIL/exit-1,
  // scaring off new devs who run the very health check `fbrain init`
  // recommends. (Empirically, on a healthy fresh brain ~3% of runs land at 3/5
  // and ~25% at 4/5 even though the average is consistently ~0.6 — the
  // all-or-nothing gate fired on all of those.) The genuine signal is "fresh
  // writes surface healthily", which is captured by a healthy *average* score
  // together with a majority of trials surfacing — NOT by every single trial
  // clearing the floor. (Same class as the pollution-probe low-N floor fixed in
  // doctor-pollution-probe-low-n-floor.)
  //
  // PASS when BOTH hold:
  //   - the average score is healthy (avgScore ≥ minScore) — the average is the
  //     stable signal; per-trial noise cancels out across trials; AND
  //   - a majority of trials surfaced at the floor (passed ≥ ceil(trials/2)) —
  //     so a high average carried by one or two outlier trials while most miss
  //     does NOT pass (that's a genuinely weak index, not noise).
  // This passes 5/5, 4/5, and the occasional 3/5 when the average is healthy,
  // while still failing a weak minority (≤ 2/5) or a systematically low average.
  const majorityThreshold = Math.ceil(trials / 2);
  const majoritySurfaced = passed >= majorityThreshold;
  const healthyAverage = avgScore !== null && avgScore >= minScore;
  if (majoritySurfaced && healthyAverage) {
    return { name: "freshness-probe", ok: true, detail };
  }

  // Genuine failure. Distinguish the two real causes so the fix line points
  // somewhere useful instead of blanket-recommending `fbrain reindex` (which
  // re-puts embeddings and does nothing for score variance or a node whose
  // writes aren't surfacing at all).
  const notSurfacing = avgScore === null || passed === 0;
  const fix = notSurfacing
    ? "fresh writes are not surfacing in search at all — this points at the node, not the index. Check the node log and confirm the embedding runtime is up (the native-index search must be returning our just-written record); restart the node with embeddings enabled if needed."
    : `fresh writes are surfacing but retrieval quality is systematically low (avg score < ${minScore} and/or only a weak minority of trials cleared the floor). Check the node's embedding model/runtime; if the live index has drifted, \`fbrain reindex\` re-puts every live record so its embedding is current (it does NOT de-duplicate the index or reduce pollution).`;
  return {
    name: "freshness-probe",
    ok: false,
    detail,
    fix,
  };
}

// G3a (pollution component) — issue one broad query and classify every hit
// into live / stale (record gone or tombstoned) / orphan (schema not an
// fbrain type). The ratio verdict (WARN above warnThreshold, default 25%)
// only applies once there are enough hits to be statistically meaningful:
// below `pollutionMinSample` (default 10) the percentage is dominated by a
// tiny denominator — a brand-new dev's own re-put/delete churn plus the
// freshness probe's own writes reads as "catastrophic" when nothing is
// wrong — so we report the raw counts with an explicit low-sample note and
// skip the threshold framing entirely. Mirrors the verbose `skip stale` /
// `skip schema_name matches no registered fbrain type` lines in `fbrain
// search`, and the same low-N discipline applied to the search weak-match
// advisory (card search-weak-match-sparse-brain-floor).
export async function runPollutionProbe(
  node: NodeClient,
  cfg: Config,
  opts: DoctorOptions,
  verbose: Verbose | undefined,
): Promise<CheckResult> {
  const query = opts.pollutionQuery ?? "fbrain";
  const warnThreshold = opts.pollutionWarnThreshold ?? 0.25;
  const failThreshold = opts.pollutionFailThreshold ?? 0.5;
  const minSample = opts.pollutionMinSample ?? 10;

  let hits: NativeIndexHit[];
  try {
    hits = await node.search(query);
  } catch (err) {
    return {
      name: "pollution-probe",
      ok: false,
      detail: `search "${query}" failed: ${errMsg(err)}`,
      fix: "check the node log; the native-index search endpoint is rejecting our query",
    };
  }
  const total = hits.length;
  if (total === 0) {
    return {
      name: "pollution-probe",
      ok: true,
      detail: `query "${query}" returned 0 hits — nothing to classify`,
    };
  }

  const typesToLoad = new Set<RecordType>();
  for (const hit of hits) {
    const slug = hit.key_value.hash;
    const type = recordTypeForHash(hit.schema_name, cfg.schemaHashes);
    if (type && slug) typesToLoad.add(type);
  }

  const liveSlugsByType = new Map<RecordType, Set<string>>();
  const failedTypes = new Set<RecordType>();
  for (const type of typesToLoad) {
    const schemaHash = cfg.schemaHashes[type]!;
    try {
      const records = await listRecords(node, type, schemaHash, cfg);
      liveSlugsByType.set(
        type,
        new Set(records.filter((r) => !r.tags.includes(TOMBSTONE_TAG)).map((r) => r.slug)),
      );
    } catch (err) {
      failedTypes.add(type);
      verbose?.(
        `pollution: listRecords threw for ${type}: ${errMsg(err)} — counting matching hits as stale`,
      );
    }
  }

  let stale = 0;
  let orphan = 0;
  let live = 0;
  for (const hit of hits) {
    const slug = hit.key_value.hash;
    const type = recordTypeForHash(hit.schema_name, cfg.schemaHashes);
    if (!type) {
      orphan++;
      verbose?.(
        `pollution: orphan schema_name="${hit.schema_name}" slug="${slug ?? "?"}"`,
      );
      continue;
    }
    if (!slug) {
      stale++;
      verbose?.(`pollution: stale (no slug) schema=${type}`);
      continue;
    }
    if (failedTypes.has(type)) {
      stale++;
      continue;
    }
    if (liveSlugsByType.get(type)?.has(slug)) {
      live++;
      verbose?.(`pollution: live ${type}/${slug}`);
    } else {
      stale++;
      verbose?.(`pollution: stale ${type}/${slug}`);
    }
  }

  // Small-sample floor: below `minSample` total hits the (stale+orphan)/total
  // ratio is low-N noise — a couple of stale embeddings from the dev's own
  // first re-put/delete (plus the freshness probe's own writes) reads as
  // "catastrophic" when nothing is wrong. Report the raw counts with an
  // explicit note and SKIP the warn/fail-threshold framing. Once there are
  // enough hits the ratio verdict below applies exactly as before.
  if (total < minSample) {
    return {
      name: "pollution-probe",
      ok: true,
      detail:
        `query "${query}" → ${total} hits: live ${live}, stale ${stale}, orphan ${orphan} ` +
        `— low sample (N=${total} < ${minSample}) — pollution % not meaningful on a small/new brain yet`,
    };
  }

  const stalePct = stale / total;
  const orphanPct = orphan / total;
  const combinedPct = (stale + orphan) / total;
  const detail =
    `query "${query}" → ${total} hits: ` +
    `live ${live}, stale ${stale} (${pct(stalePct)}), orphan ${orphan} (${pct(orphanPct)}) ` +
    `— pollution ${pct(combinedPct)}`;
  // Pollution = stale/superseded embeddings that fold_db's append-only index
  // does NOT purge on soft-delete or re-put. No fbrain-layer action can lower
  // it today (the purge is upstream G3d/G3e work), and `reindex` makes it
  // WORSE — each re-put appends a fresh embedding while the prior one persists
  // as stale. So a high ratio must surface as a WARN (visible, counted) and
  // must NOT fail the verdict or recommend `reindex`. See the honest hint.
  const pollutionHint =
    "stale/superseded embeddings — fold_db's append-only index does not purge them on soft-delete or re-put. " +
    "No fbrain command can lower this: `fbrain reindex` refreshes live embeddings but does NOT reduce pollution " +
    "(each re-put appends a new embedding and the prior one persists as stale). The index purge is tracked upstream. " +
    "User-facing search/ask is unaffected: they skip stale hits at query time; this is raw-index bloat, not wrong results.";
  if (combinedPct > failThreshold) {
    return {
      name: "pollution-probe",
      ok: true,
      tag: "WARN",
      detail: `${detail} (above ${pct(failThreshold)} fail-threshold, but not a verdict failure — see fix)`,
      fix: pollutionHint,
    };
  }
  if (combinedPct > warnThreshold) {
    return {
      name: "pollution-probe",
      ok: true,
      tag: "WARN",
      detail,
      fix: pollutionHint,
    };
  }
  return { name: "pollution-probe", ok: true, detail };
}

function defaultNonce(): string {
  // Lowercase hex from Date.now() + a random 24-bit suffix. Stays inside
  // the slug character set ([a-z0-9-_]).
  const rand = Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, "0");
  return `${Date.now().toString(36)}${rand}`;
}

function pct(n: number): string {
  return `${(n * 100).toFixed(0)}%`;
}

// Write-readiness probe — asks the two questions any mutation needs to
// answer "yes" to:
//   (a) is a valid CapabilityToken cached locally for this node? (load it,
//       run the same JCS integrity check the write path uses before replay).
//   (b) does the node's app registry know about fbrain? (GET
//       /api/apps/consent-request/fbrain and read the discriminated result).
// Read-only: plain doctor never creates a pending consent request.
// Fails closed: any indeterminate state (consent endpoint 5xx / throws,
// keychain unreadable) surfaces as WARN, never silently PASS.
export async function runWriteReadyProbe(
  node: NodeClient,
  nodeUrl: string,
  store: CapabilityStore,
  verbose: Verbose | undefined,
): Promise<CheckResult> {
  // Client-side enforcement OFF means fbrain won't attach capability headers,
  // and on a node ALSO running enforcement-off writes land as NodeOwner with
  // no consent step at all. We can't introspect the node's setting, so we
  // declare the limitation: WARN so the doctor verdict stays green for the
  // dogfood case but the user sees the half-configured state.
  if (!appIdentityEnforceEnabled()) {
    verbose?.(`write-ready: enforcement off — emitting WARN`);
    return {
      name: "write-ready",
      ok: true,
      tag: "WARN",
      detail:
        "client app-identity enforcement is OFF (FBRAIN_APP_IDENTITY_ENFORCE) — " +
        "no capability check performed; writes will succeed only if the node also has enforcement off",
    };
  }

  // (a) Local capability check — load from the store + JCS-integrity-validate.
  // Mirrors the gate in CapabilitySession.loadValidCached() so this probe
  // never reports PASS for a cached token the write path would discard.
  let capabilityValid = false;
  let capabilityDetail = "no capability stored for this node";
  try {
    const cached = await store.load(nodeUrl);
    if (cached === null) {
      capabilityDetail = "no capability stored for this node";
    } else {
      const token = decodeCapabilityBlob(cached.blob);
      if (token === null) {
        capabilityDetail = "stored capability blob did not decode";
      } else if (token.app_id !== FBRAIN_APP_ID) {
        capabilityDetail = `stored capability is for app_id "${token.app_id}", not "${FBRAIN_APP_ID}"`;
      } else if (!(await tokenIntegrityValid(token))) {
        capabilityDetail = "stored capability failed JCS integrity check (tampered or stale)";
      } else {
        capabilityValid = true;
      }
    }
  } catch (err) {
    // The store path itself failed (keychain locked, file unreadable, …)
    // — we can't tell if writes would work or not, so WARN.
    verbose?.(
      `write-ready: capability store load threw — ${errMsg(err)}`,
    );
    return {
      name: "write-ready",
      ok: true,
      tag: "WARN",
      detail: `could not read capability store: ${errMsg(err)}`,
      fix: "check OS keychain access and ~/.fbrain/capabilities.json, then re-run `fbrain doctor`",
    };
  }
  verbose?.(`write-ready: capability=${capabilityValid ? "valid" : `absent (${capabilityDetail})`}`);

  // (b) Node app-registration check — GET consent-request and read the
  // discriminated result. `not_registered` is the cold-registry failure;
  // pending/expired/no_pending/already_granted all prove the app is known.
  let registered: boolean;
  let registrationDetail = "";
  try {
    const res = await node.rawCall(
      "GET",
      `/api/apps/consent-request/${encodeURIComponent(FBRAIN_APP_ID)}`,
    );
    if (res.status !== 200) {
      verbose?.(`write-ready: consent-request returned HTTP ${res.status} — emitting WARN`);
      return {
        name: "write-ready",
        ok: true,
        tag: "WARN",
        detail: `consent-request lookup returned HTTP ${res.status}; cannot determine write-readiness`,
        fix: "inspect the node log; once /api/apps/consent-request/fbrain responds cleanly, re-run `fbrain doctor`",
      };
    }
    const result = readResultString(res.json);
    if (result === "not_registered") {
      registered = false;
      registrationDetail = "node returned not_registered from /api/apps/consent-request/fbrain";
    } else if (
      result === "pending" ||
      result === "expired" ||
      result === "no_pending" ||
      result === "already_granted"
    ) {
      registered = true;
    } else {
      verbose?.(`write-ready: consent-request returned result=${result ?? "?"} — emitting WARN`);
      return {
        name: "write-ready",
        ok: true,
        tag: "WARN",
        detail: `consent-request lookup returned an unrecognized result; cannot determine write-readiness`,
        fix: "inspect the node log; once /api/apps/consent-request/fbrain returns a known result, re-run `fbrain doctor`",
      };
    }
  } catch (err) {
    verbose?.(
      `write-ready: consent-request lookup threw — ${errMsg(err)}`,
    );
    return {
      name: "write-ready",
      ok: true,
      tag: "WARN",
      detail: `consent-request lookup threw: ${stripDoctorTip(errMsg(err))}`,
      fix: "inspect the node log; the consent-request endpoint is rejecting fbrain's probe",
    };
  }

  // Verdict — registration is the more actionable failure (capability is
  // moot without it), so it sorts first.
  if (!registered) {
    return {
      name: "write-blocked",
      ok: false,
      detail: `node does not recognise app "${FBRAIN_APP_ID}"${registrationDetail ? ` (${registrationDetail})` : ""}`,
      fix:
        "the node's app registry has no fbrain entry — every write will fail with `app_not_registered`. " +
        "Restart the daemon to warm the registry, or wait for the app_identity publish path to land if you're mid-migration " +
        "(`folddb-dev app publish --id fbrain` on the dev side).",
    };
  }
  if (!capabilityValid) {
    return {
      name: "write-blocked",
      ok: false,
      detail: capabilityDetail,
      fix:
        "run `fbrain init --grant-consent` to grant consent and store a capability — it works whether or not you have an interactive terminal (bare `fbrain init` skips the consent prompt without a TTY, so it no-ops here and loops). " +
        "It's idempotent, so it's safe interactively too (or run any write command — they all run the consent handshake on first use). " +
        "On the daemon side the grant is confirmed with `lastdb consent grant fbrain`.",
    };
  }
  return {
    name: "write-ready",
    ok: true,
    detail: "capability cached + JCS-valid for this node; app registry lookup is read-only and recognizes fbrain",
  };
}

// MCP-entrypoint probe — resolve the `fbrain-mcp` bin on PATH so a new dev
// can see whether `claude mcp add fbrain fbrain-mcp` (the headline agent
// integration the README front-loads) will actually work. package.json `bin`
// declares both `fbrain` and `fbrain-mcp`, but a stale hand-installed `fbrain`
// shim can leave `fbrain` resolvable while `fbrain-mcp` is missing — and that
// breakage is otherwise invisible (the agent just can't reach the brain).
//
// Cheap + offline: PATH resolution via Bun.which only — we never spawn the
// MCP server. WARN (never FAIL) when unresolved so the verdict stays green
// for CLI-only users and source-checkout users (who register the path-based
// form), with an actionable re-link hint. PASS message carries the resolved
// path.
// Runtime probe — compare the running Bun against fbrain's documented minimum.
// PASS when `Bun.version >= MIN_BUN_VERSION` (single-sourced from
// package.json `engines.bun`); FAIL (not WARN — too old a runtime is a real
// blocker, not an optional nicety) with an actionable upgrade hint when older.
// The running version is injected via `bunVersion` (defaults to `Bun.version`)
// so both branches are testable without depending on the host's installed Bun.
// Cheap + offline: a pure version string compare, never touches the node.
export function runRuntimeProbe(
  opts: DoctorOptions,
  verbose: Verbose | undefined,
): CheckResult {
  const found = opts.bunVersion ?? Bun.version;
  if (bunVersionMeetsMinimum(found, MIN_BUN_VERSION)) {
    verbose?.(`runtime: Bun ${found} (>= ${MIN_BUN_VERSION})`);
    return {
      name: "runtime",
      ok: true,
      detail: `Bun ${found} (>= ${MIN_BUN_VERSION})`,
    };
  }
  verbose?.(`runtime: Bun ${found} is older than ${MIN_BUN_VERSION} — FAIL`);
  return {
    name: "runtime",
    ok: false,
    detail: `Bun ${found} is older than fbrain's minimum (${MIN_BUN_VERSION})`,
    fix:
      `your Bun (${found}) is older than fbrain's minimum (${MIN_BUN_VERSION}). ` +
      "Upgrade: `brew upgrade bun` (or `bun upgrade`), then re-run.",
  };
}


export async function runWriteRoundtripProbe(
  cfg: Config,
  opts: DoctorOptions,
  verbose: Verbose | undefined,
): Promise<CheckResult> {
  const conceptHash = cfg.schemaHashes.concept;
  if (!conceptHash) {
    return {
      name: "write-roundtrip",
      ok: false,
      detail: 'config has no schemaHashes["concept"]',
      fix: "re-run `fbrain init` so the config picks up all schema hashes",
    };
  }

  const nonce = (opts.nonceFn ?? defaultNonce)();
  const slug = `doctor-write-roundtrip-${nonce}`;

  const wnOpts: WriteNodeClientOptions = {
    baseUrl: cfg.nodeUrl,
    userHash: cfg.userHash,
  };
  if (verbose) wnOpts.verbose = verbose;
  if (opts.capabilityStore) wnOpts.store = opts.capabilityStore;
  const { node } = (opts.writeNodeFactory ?? newWriteNodeClient)(wnOpts);

  let created = false;
  try {
    const now = nowIso();
    await node.createRecord({
      schemaHash: conceptHash,
      keyHash: slug,
      fields: {
        slug,
        title: `doctor write-roundtrip probe ${nonce}`,
        body:
          `Doctor --write round-trip probe. Slug: ${slug}. ` +
          `Generated by \`fbrain doctor --write\` — safe to delete.`,
        status: "active",
        tags: [],
        created_at: now,
        updated_at: now,
      },
    });
    created = true;

    const echo = await verifyRecordVisible(node, "concept", conceptHash, slug);
    if (!echo) {
      return {
        name: "write-roundtrip",
        ok: false,
        detail: `wrote ${slug} but a subsequent read returned null`,
        fix: "the create reported success but the record isn't readable — inspect the node log",
      };
    }
    return {
      name: "write-roundtrip",
      ok: true,
      detail: `put → get → soft-delete round-trip succeeded under slug "${slug}"`,
    };
  } catch (err) {
    return {
      name: "write-roundtrip",
      ok: false,
      detail: stripDoctorTip(errMsg(err)),
      fix: "the round-trip write failed — see the error above and the node log; check `fbrain doctor` for the write-ready / consent status",
    };
  } finally {
    if (created) {
      try {
        const cleanupFields = buildTombstoneFields("concept", slug, nowIso(), nowIso());
        await node.updateRecord({ schemaHash: conceptHash, fields: cleanupFields, keyHash: slug });
      } catch (err) {
        verbose?.(
          `write-roundtrip cleanup failed for ${slug}: ${errMsg(err)}`,
        );
      }
    }
  }
}

// Schema-service publish-gate probe used when there is no config yet (init
// hasn't completed). Issues one POST /v1/schemas against the configured
// schema service and translates the discriminated `cert_required` response
// into a structured FAIL with the same remedy text the init error carries.
// Other outcomes are squashed to a single WARN so the probe never overstates
// confidence on a network-flaky run — the real publish path is `fbrain init`.
//
// `schemaClientFactory` (from opts) lets tests stub the schema service; in
// production we use the default factory pointed at the URL from opts.nodeUrl
// / opts.schemaServiceUrl or the init defaults when the user has no config.

function readResultString(body: unknown): string | undefined {
  if (body && typeof body === "object" && "result" in body) {
    const v = (body as Record<string, unknown>).result;
    if (typeof v === "string" && v.length > 0) return v;
  }
  return undefined;
}

function errMsg(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
